import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'
import globals from 'globals'
import tseslint from 'typescript-eslint'

// ──────────────────────────────────────────────────────────────────────────────
// Root ESLint config for the TaylorDB Forms template
// ──────────────────────────────────────────────────────────────────────────────
//
// Why an `any`-ban?
// -----------------
// `defineForm` from `@taylordb/forms-core` attaches default validators that are
// strict about the runtime shape of an answer (e.g. `multiple_choice` expects
// `string[]`). Coercing through `any` on the client/server boundary is the
// fastest way to silently break autosave validation against TaylorDB columns
// like `singleSelect` (which stores a string). Keep `any` out of the codebase
// and unwrap/wrap values explicitly at the `queryBuilder` boundary instead.
//
// `no-explicit-any` is **error** so the lint will block `: any` and
// `as any` casts at review time.
//
// The `no-unsafe-*` family (which would catch reading off untyped values
// at call sites) requires type-aware linting and a project-wide TS
// program, which is heavier to set up. The current config sticks to the
// fast non-typed rules; promote to typed linting later if needed.
//
// `apps/server/taylordb/types.ts` is generated by the TaylorDB CLI — see
// AGENTS.md rule 2. It is ignored below so the generated `any`s don't trip
// the rule.

export default defineConfig([
  globalIgnores([
    'dist',
    '**/dist/**',
    '**/node_modules/**',
    // Generated by `pnpm generate:schema`. Never edit; never lint.
    'apps/server/taylordb/types.ts',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // Hard ban on `any` — both annotations (`: any`) and casts
      // (`as any`, `<any>x`). See the comment block at the top of this
      // file for why this matters for the forms-core ↔ TaylorDB
      // boundary.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
])
