# yaml-language-server: $schema=https://server-vms.develop.taylordb.ai/apps/config-schema/v1

version: 1

project: blank

runtime:
  type: node
  version: 20
  packageManager: pnpm

services:
  web:
    workDir: apps/web
    install:
      commands:
        - pnpm install
    dev:
      command: pnpm dev
      port: 3000
      env:
        vars:
          TAYLORDB_BASE_URL: vars.TAYLORDB_INTERNAL_BASE_URL
          TAYLORDB_SERVER_ID: vars.TAYLORDB_SERVER_ID
    start:
      command: pnpm preview
      port: 3000
      env:
        vars:
          TAYLORDB_BASE_URL: vars.TAYLORDB_INTERNAL_BASE_URL
          TAYLORDB_SERVER_ID: vars.TAYLORDB_SERVER_ID
    build:
      commands:
        - pnpm build
      env:
        vars:
          TAYLORDB_BASE_URL: vars.TAYLORDB_INTERNAL_BASE_URL
          TAYLORDB_SERVER_ID: vars.TAYLORDB_SERVER_ID

taylordb:
  version: 0.18.1
  types:
    - output: apps/web/src/server/taylordb/types.ts
      format: typescript
      onChange:
        - pnpm lint

preview:
  service: web

routing:
  - path: /
    service: web
