/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadFormFileRouteImport } from './routes/api/upload-form-file'
import { Route as ApiFormsActionRouteImport } from './routes/api/forms/$action'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadFormFileRoute = ApiUploadFormFileRouteImport.update({
  id: '/api/upload-form-file',
  path: '/api/upload-form-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsActionRoute = ApiFormsActionRouteImport.update({
  id: '/api/forms/$action',
  path: '/api/forms/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/upload-form-file': typeof ApiUploadFormFileRoute
  '/api/forms/$action': typeof ApiFormsActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/upload-form-file': typeof ApiUploadFormFileRoute
  '/api/forms/$action': typeof ApiFormsActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/upload-form-file': typeof ApiUploadFormFileRoute
  '/api/forms/$action': typeof ApiFormsActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/upload-form-file' | '/api/forms/$action'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/upload-form-file' | '/api/forms/$action'
  id: '__root__' | '/' | '/$' | '/api/upload-form-file' | '/api/forms/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiUploadFormFileRoute: typeof ApiUploadFormFileRoute
  ApiFormsActionRoute: typeof ApiFormsActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-form-file': {
      id: '/api/upload-form-file'
      path: '/api/upload-form-file'
      fullPath: '/api/upload-form-file'
      preLoaderRoute: typeof ApiUploadFormFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$action': {
      id: '/api/forms/$action'
      path: '/api/forms/$action'
      fullPath: '/api/forms/$action'
      preLoaderRoute: typeof ApiFormsActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiUploadFormFileRoute: ApiUploadFormFileRoute,
  ApiFormsActionRoute: ApiFormsActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
